name: CI & Docker Build

on: [push]

jobs:
  train-and-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run MLflow Project
        run: |
          cd MLProject
          mlflow run .
      
      - name: Show mlruns location
        run: |
          find . -name mlruns -type d

      - name: Upload model artifact
        uses: actions/upload-artifact@v4
        with:
          name: hasil-training-mlflow
          path: |
            mlruns/

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker
        run: |
          # Karena kita pakai local storage (bukan registry), 
          # kita gunakan docker build standar. 
          # Pastikan file 'Dockerfile' Anda sudah benar di root.
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/loan-scoring:latest .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/loan-scoring:latest